pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "layout"
    - "permalink"
    - "noindex"
    - "date"
    - "override"
    - "codelabs"
    - "tags"
    - "authors"

    ignore_patterns:
    - !ruby/regexp /{%\s((?!{%)[\s\S])*\s%}/
    - !ruby/regexp /{%\s?([a-zA-Z0-9\.,\-\?\'\"\s]*)\s?%}/    

  paths:
  - source: site/en/docs/privacy-sandbox
    include:
      - "attribution-reporting/summary-reports/*.*"
